version: '3'
services:
    db:
        image: mongo
        ports:
            - "27017:27017"    
        volumes:
            - mongostorage:/home
        networks:
           - main            
    web:
        build: .
        command: python3 mysite/manage.py runserver 0.0.0.0:8000
        networks:
            - main
        volumes:
            - .:/workspace
        ports:
            - "8000:8000"
        depends_on:
            - db
     
networks:
    main:

volumes:
    mongostorage:
