version: "3"
services:
    web:
        build: .
        restart: always
        command: pipenv run  gunicorn --bind 0.0.0.0:8080 bailey.wsgi:application
        #command: pipenv run ./bailey/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/www
        ports:
            - "8000:8000"
        depends_on:
            - nginx
        env_file:
            - secret.env

    nginx:
        image: "nginx"
        restart: always
        volumes:
            - ./nginx/:/etc/nginx/conf.d/
        ports:
            - "80:80"
            - "443:443"
        extra_hosts:
            - "dockerhost:$DOCKERHOST"

