version: "3"
services:
    web:
        build: .
        restart: always
        #command: pipenv run  gunicorn --bind 0.0.0.0:8000 bailey.wsgi:application
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/www
        ports:
            - "8000:8000"
        depends_on:
            - nginx
        env_file:
            - secret.env

    nginx:
        image: "nginx"
        restart: always
        volumes:
            - ./nginx/:/etc/nginx/conf.d/
            - /etc/letsencrypt/:/etc/letsencrypt/
        ports:
            #Outward facing
            - "80:80"
            - "443:443"
        extra_hosts:
            - "dockerhost:$DOCKERHOST"

